# Generated by Django 5.0.6 on 2026-05-10 01:26

import apps.attendance.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('signature', models.ImageField(blank=True, null=True, upload_to=apps.attendance.models.signature_upload_to)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.attendance.models.photo_upload_to)),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('tidak_hadir', 'Tidak Hadir')], default='hadir', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='participants.participant')),
            ],
            options={
                'ordering': ['-attendance_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('event', 'participant'), name='unique_attendance_per_event_participant'),
        ),
    ]
