# Generated by Django 5.0.6 on 2026-05-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='SILAKHADIR', max_length=120)),
                ('tagline', models.CharField(default='Absensi Online dan Sertifikat Digital Kegiatan', max_length=200)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('head_name', models.CharField(blank=True, max_length=150)),
                ('head_position', models.CharField(blank=True, max_length=150)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('stamp_image', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#0b2d6b', max_length=20)),
                ('secondary_color', models.CharField(default='#d1a827', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Aplikasi',
                'verbose_name_plural': 'Pengaturan Aplikasi',
            },
        ),
    ]
