# Generated by Django 5.0.6 on 2026-05-10 01:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_type', models.CharField(choices=[('NIK', 'NIK'), ('NIP', 'NIP')], default='NIK', max_length=3)),
                ('identity_number', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[0-9]{8,32}$', 'Angka saja, minimal 8 digit.')])),
                ('full_name', models.CharField(max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('event', 'identity_number'), name='unique_participant_per_event'),
        ),
    ]
