# Generated by Django 5.0.6 on 2026-05-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('background_image', models.ImageField(upload_to='cert_templates/')),
                ('signer_name', models.CharField(blank=True, max_length=150)),
                ('signer_position', models.CharField(blank=True, max_length=150)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='cert_signs/')),
                ('stamp_image', models.ImageField(blank=True, null=True, upload_to='cert_stamps/')),
                ('name_position_x', models.FloatField(default=50)),
                ('name_position_y', models.FloatField(default=45)),
                ('event_position_x', models.FloatField(default=50)),
                ('event_position_y', models.FloatField(default=58)),
                ('date_position_x', models.FloatField(default=50)),
                ('date_position_y', models.FloatField(default=70)),
                ('qr_position_x', models.FloatField(default=10)),
                ('qr_position_y', models.FloatField(default=85)),
                ('number_position_x', models.FloatField(default=50)),
                ('number_position_y', models.FloatField(default=30)),
                ('name_font_size', models.PositiveSmallIntegerField(default=36)),
                ('event_font_size', models.PositiveSmallIntegerField(default=20)),
                ('date_font_size', models.PositiveSmallIntegerField(default=16)),
                ('number_font_size', models.PositiveSmallIntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
