# Generated by Django 5.0.6 on 2026-05-10 01:26

import apps.certificates.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.certificates.models.certificate_pdf_upload)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=apps.certificates.models.certificate_qr_upload)),
                ('verification_token', models.CharField(max_length=64, unique=True)),
                ('download_token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('diproses', 'Diproses'), ('dicabut', 'Dicabut')], default='tersedia', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='events.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='participants.participant')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('event', 'participant'), name='unique_certificate_per_event_participant'),
        ),
    ]
