# Generated by Django 5.0.6 on 2026-05-10 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateNumberFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('pattern', models.CharField(default='{seq3}/SIAKADIR/{event}/{month_roman}/{year}', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('use_global_counter', models.BooleanField(default=False)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='source',
            field=models.CharField(choices=[('generated', 'Generated Otomatis'), ('uploaded', 'Upload Manual')], default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='number_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.certificatenumberformat'),
        ),
    ]
