# Generated by Django 5.0.6 on 2026-05-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificatenumberformat_certificate_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(max_length=100),
        ),
    ]
