# Generated by Django 4.2.30 on 2026-07-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jabatan',
            field=models.CharField(blank=True, help_text='Jabatan pegawai.', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='nip',
            field=models.CharField(blank=True, help_text='Nomor Induk Pegawai (NIP) ASN.', max_length=20, null=True, unique=True),
        ),
    ]
