# Generated by Django 5.0.6 on 2026-05-10 14:04

import apps.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreport',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover laporan (gambar full A4, ditampilkan di halaman pertama).', null=True, upload_to=apps.reports.models.report_cover_upload),
        ),
    ]
