# Generated by Django 4.2.30 on 2026-07-06 10:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeKinerja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(help_text='Nama periode, e.g. "Juli 2026 - Bidang Pemerintahan Digital".', max_length=255)),
                ('bulan', models.PositiveIntegerField(help_text='Bulan (1-12).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('tahun', models.PositiveIntegerField(help_text='Tahun, e.g. 2026.')),
                ('bidang', models.CharField(help_text='Nama bidang, e.g. "Pemerintahan Digital".', max_length=255)),
                ('deskripsi', models.TextField(blank=True, help_text='Deskripsi atau catatan untuk periode ini.')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('ditutup', 'Ditutup')], default='aktif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Periode Kinerja',
                'verbose_name_plural': 'Periode Kinerja',
                'ordering': ['-tahun', '-bulan'],
                'unique_together': {('bulan', 'tahun', 'bidang')},
            },
        ),
        migrations.CreateModel(
            name='KinerjaHarian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal', models.DateField(help_text='Tanggal kegiatan dilakukan.')),
                ('uraian_kegiatan', models.TextField(help_text='Deskripsi kegiatan yang dilakukan.')),
                ('output', models.CharField(help_text='Hasil/output kegiatan, e.g. "Dokumen Rancangan Sistem".', max_length=255)),
                ('volume', models.DecimalField(decimal_places=2, default=1, help_text='Jumlah/volume pekerjaan.', max_digits=10)),
                ('satuan', models.CharField(help_text='Satuan, e.g. "Dokumen", "Kegiatan", "Laporan".', max_length=100)),
                ('keterangan', models.TextField(blank=True, help_text='Catatan tambahan (opsional).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinerja_entries', to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinerja_entries', to='kinerja.periodekinerja')),
            ],
            options={
                'verbose_name': 'Kinerja Harian',
                'verbose_name_plural': 'Kinerja Harian',
                'ordering': ['tanggal', 'created_at'],
            },
        ),
    ]
