# Generated by Django 4.2.30 on 2026-07-06 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kinerja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinerjaharian',
            name='link_bukti',
            field=models.URLField(blank=True, help_text='Link bukti dukung (opsional), e.g. Google Drive link.', max_length=500),
        ),
        migrations.AddField(
            model_name='kinerjaharian',
            name='nama_pegawai',
            field=models.CharField(default='', help_text='Nama lengkap pegawai.', max_length=200),
        ),
        migrations.AddField(
            model_name='kinerjaharian',
            name='nip_pegawai',
            field=models.CharField(default='', help_text='NIP pegawai.', max_length=20),
        ),
        migrations.AddField(
            model_name='periodekinerja',
            name='public_slug',
            field=models.SlugField(blank=True, help_text='Slug unik untuk link form publik pengisian kinerja.', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='kinerjaharian',
            name='pegawai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kinerja_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
