# Generated by Django 4.2.30 on 2026-07-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0002_kinerjaharian_link_bukti_kinerjaharian_nama_pegawai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinerjaharian',
            name='email_pegawai',
            field=models.EmailField(blank=True, default='', help_text='Surel pegawai.', max_length=254),
        ),
        migrations.AddField(
            model_name='kinerjaharian',
            name='no_hp_pegawai',
            field=models.CharField(blank=True, default='', help_text='Nomor HP/handphone pegawai.', max_length=20),
        ),
        migrations.AlterField(
            model_name='kinerjaharian',
            name='satuan',
            field=models.CharField(blank=True, help_text='Satuan, e.g. "Dokumen", "Kegiatan", "Laporan".', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kinerjaharian',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='Jumlah/volume pekerjaan.', max_digits=10, null=True),
        ),
    ]
