# Generated by Django 4.2.30 on 2026-07-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0003_kinerjaharian_email_pegawai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinerjaharian',
            name='output',
            field=models.CharField(blank=True, help_text='Hasil/output kegiatan, e.g. "Dokumen Rancangan Sistem".', max_length=255, null=True),
        ),
    ]
