# Generated by Django 4.2.30 on 2026-07-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0004_alter_kinerjaharian_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinerjaharian',
            name='jabatan_pegawai',
            field=models.CharField(blank=True, default='', help_text='Jabatan pegawai.', max_length=200),
        ),
    ]
