# Generated by Django 4.2.30 on 2026-07-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0005_kinerjaharian_jabatan_pegawai'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodekinerja',
            name='kepala_bidang_nama',
            field=models.CharField(blank=True, default='', help_text='Nama Kepala Bidang untuk penandatanganan.', max_length=255),
        ),
        migrations.AddField(
            model_name='periodekinerja',
            name='kepala_bidang_nip',
            field=models.CharField(blank=True, default='', help_text='NIP Kepala Bidang untuk penandatanganan.', max_length=50),
        ),
    ]
