# Generated by Django 5.0.6 on 2026-07-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0006_periodekinerja_kepala_bidang_nama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodekinerja',
            name='google_form_url',
            field=models.URLField(blank=True, default='', help_text='URL Google Form untuk pengisian kinerja harian. Setiap kinerja yang disubmit akan otomatis dikirim ke form ini. Contoh: https://docs.google.com/forms/d/xxx/viewform', max_length=500),
        ),
    ]
