# Generated by Django 5.0.6 on 2026-07-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinerja', '0007_add_google_form_url_to_periodekinerja'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodekinerja',
            name='gform_entry_link_bukti',
            field=models.CharField(blank=True, default='', help_text='Entry ID field Link Bukti Dukung di Google Form (opsional).', max_length=50),
        ),
        migrations.AddField(
            model_name='periodekinerja',
            name='gform_entry_nama',
            field=models.CharField(blank=True, default='', help_text='Entry ID field Nama di Google Form. Contoh: entry.123456789', max_length=50),
        ),
        migrations.AddField(
            model_name='periodekinerja',
            name='gform_entry_nip',
            field=models.CharField(blank=True, default='', help_text='Entry ID field NIP di Google Form. Contoh: entry.987654321', max_length=50),
        ),
        migrations.AddField(
            model_name='periodekinerja',
            name='gform_entry_tanggal',
            field=models.CharField(blank=True, default='', help_text='Entry ID field Tanggal di Google Form (opsional).', max_length=50),
        ),
        migrations.AddField(
            model_name='periodekinerja',
            name='gform_entry_uraian',
            field=models.CharField(blank=True, default='', help_text='Entry ID field Uraian Kegiatan di Google Form. Contoh: entry.111222333', max_length=50),
        ),
        migrations.AlterField(
            model_name='periodekinerja',
            name='google_form_url',
            field=models.URLField(blank=True, default='', help_text='URL Google Form harian. Contoh: https://docs.google.com/forms/d/xxx/viewform', max_length=500),
        ),
    ]
